import { prisma } from '../../lib/prisma.js'
import { Category, CategoryLabel, CategoryIcon } from '../../constants/business.js'

/**
 * 全量标签池（约 1000 个），覆盖 AI 领域多个维度。
 * 发帖时输入自动补全，首页头部随机展示 5 个。
 *
 * 维度：
 *   大语言模型 | 图像模型 | 视频模型 | 音频模型 | AI编程
 *   | 平台工具 | 技术方法 | 框架库 | 公司机构 | 论文
 *   | 数据集 | 概念术语 | 应用领域 | 国产AI | 开源项目
 *   | Prompt工程 | Agent | 多模态 | 部署运维 | AI安全
 */
const TAGS = [
  // ── 大语言模型 (LLMs) ──
  'GPT-5', 'GPT-4o', 'GPT-4', 'GPT-4-Turbo', 'GPT-3.5',
  'o4', 'o4-mini',
  'Claude', 'Claude Opus', 'Claude Sonnet', 'Claude Haiku',
  'Gemini', 'Gemini 2.5', 'Gemini 2.0', 'Gemma',
  'DeepSeek', 'DeepSeek V4', 'DeepSeek R2', 'DeepSeek Coder',
  'Qwen', 'Qwen 3', 'Qwen 2.5', 'QwQ',
  'Llama', 'Llama 4', 'Llama 3', 'Code Llama',
  'Mistral', 'Mixtral', 'Mistral Large',
  'Grok', 'Grok 4',
  'Yi', 'Yi-Lightning', 'Yi-Vision',
  'Command R+', 'Cohere',
  'Phi', 'Phi-4', 'Phi-3',
  'Falcon', 'MPT', 'DBRX',
  'Jamba', 'Granite', 'OLMo', 'DCLM',
  'BLOOM', 'Baichuan', 'ChatGLM', 'InternLM',
  'MiniCPM', 'Skywork', 'TeleChat',
  'Reka', 'Aya', 'SeaLLM', 'SOLAR',
  'Nemotron', 'Arctic',

  // ── 推理模型 ──
  '推理模型', 'Chain-of-Thought', 'Tree-of-Thought', 'Self-Consistency',
  'ReAct', 'Auto-CoT', 'Reflexion', 'Self-Refine',

  // ── 图像模型 ──
  'Stable Diffusion', 'SDXL', 'SD3.5', 'SD3', 'Stable Cascade',
  'Flux', 'Flux Pro', 'Flux Dev', 'Flux Schnell',
  'Midjourney', 'Midjourney V7', 'Midjourney V6',
  'DALL-E', 'DALL-E 4',
  'AuraFlow', 'Playground', 'PixArt',
  'Kolors', 'Hunyuan-DiT',
  'Ideogram', 'Imagen',

  // ── 视频模型 ──
  'Sora', 'Sora Turbo',
  'Runway', 'Runway Gen-4', 'Runway Gen-3',
  'Kling', 'Kling 2.0',
  'Pika', 'Pika 2.0',
  'Luma Dream Machine', 'Luma Ray2',
  'Hailuo', 'Vidu',
  'PixVerse', 'Mochi',
  'Stable Video Diffusion',
  'CogVideoX', 'AnimateDiff', 'Hotshot',
  'Emu Video', 'VideoPoet',

  // ── 3D 模型 ──
  '3D生成', 'NeRF', 'Gaussian Splatting', 'TripoSR',
  'Meshy', 'Luma Genie', 'Shap-E', 'Zero-1-to-3',

  // ── 音频/语音模型 ──
  'Whisper', 'Whisper Large', 'WhisperX', 'faster-whisper',
  'ElevenLabs', 'ElevenLabs Turbo',
  'Suno', 'Suno V5', 'Udio',
  'Bark', 'XTTS', 'StyleTTS',
  'MusicGen', 'AudioGen', 'MusicLM',
  'CosyVoice', 'ChatTTS', 'FishSpeech',
  'Parler-TTS', 'MeloTTS', 'OpenVoice',
  'Stable Audio', 'AudioCraft', 'MMAudio',
  'F5-TTS', 'Spark-TTS',

  // ── AI 编程 ──
  'Copilot', 'GitHub Copilot', 'Copilot X',
  'Cursor', 'Cursor Agent', 'Cursor Composer',
  'Cline', 'Aider', 'Devin',
  'Codeium', 'Windsurf', 'Supermaven',
  'Amazon Q Developer', 'Tabnine', 'Sourcegraph Cody',
  'Replit Agent', 'Bolt.new', 'Lovable',
  'v0.dev', 'Claude Code', 'Gemini Code Assist',
  'Continue.dev', 'OpenHands', 'SWE-Agent',
  'CodeGeeX', 'TONGYI Lingma',
  'Sweep', 'Plandex', 'Qodo',

  // ── AI 工具 / 平台 ──
  'Dify', 'Coze', '扣子',
  'Ollama', 'vLLM', 'SGLang', 'LM Studio', 'llama.cpp',
  'GPT4All', 'Jan', 'Oobabooga', 'text-generation-webui',
  'ComfyUI', 'Automatic1111', 'InvokeAI', 'Fooocus',
  'Draw Things', 'Diffusion Bee',
  'HuggingFace', 'HuggingFace Spaces', 'Gradio', 'Streamlit', 'Chainlit',
  'Replicate', 'Together AI', 'Fireworks AI', 'Groq', 'Anyscale',
  'OpenRouter', 'DeepInfra', 'Baseten', 'Modal', 'RunPod',
  'Weights & Biases', 'MLflow', 'ClearML', 'Neptune', 'Comet',
  'LangSmith', 'LangFuse', 'Arize', 'Phoenix',
  'VectorAdmin', 'Chroma', 'Qdrant Cloud', 'Pinecone',
  'Vercel AI SDK', 'Cloudflare AI', 'Workers AI',
  'Notion AI', 'Mem.ai', 'Reflect',
  'Perplexity', 'Phind', 'You.com', 'Kagi', 'Exa',
  'Airtable AI', 'Zapier AI', 'Make AI',

  // ── 低代码/无代码 AI ──
  'n8n', 'Flowise', 'LangFlow', 'Relevance AI',
  'Vellum', 'Dust', 'Wordware',

  // ── 监控/可观测性 ──
  'LLMOps', 'PromptLayer', 'Helicone', 'OpenMeter', 'Braintrust',

  // ── 技术/方法 ──
  'RAG', 'Advanced RAG', 'Graph RAG', 'Agentic RAG', 'HyDE',
  'Fine-tuning', 'SFT', 'RLHF', 'DPO', 'PPO', 'KTO',
  'LoRA', 'QLoRA', 'DoRA', 'VeRA',
  'Prompt Engineering', 'Few-shot', 'Zero-shot', 'In-Context Learning',
  'Mixture of Experts', 'MoE',
  'Transformer', 'Self-Attention', 'Cross-Attention', 'FlashAttention',
  'Tokenization', 'BPE', 'SentencePiece', 'TikToken',
  'Embedding', 'Text Embedding', 'BGE', 'E5', 'Voyage',
  'Vector Search', 'Semantic Search', 'Hybrid Search',
  'KV Cache', 'KV Cache量化',
  'Speculative Decoding', 'Medusa',
  'Distillation', 'Quantization', 'GGUF', 'GPTQ', 'AWQ', 'bitsandbytes',
  'Pruning', 'Sparsity', 'MoEfication',
  'RLHF', 'Constitutional AI', 'CAI',
  'Diffusion Models', 'Score-based Models', 'Flow Matching',
  'GAN', 'VAE', 'Normalizing Flows',
  'CLIP', 'SigLIP', 'BLIP',
  'Contrastive Learning', 'SimCLR', 'MoCo',
  'Self-Supervised Learning', 'Masked Autoencoder',
  'Transfer Learning', 'Curriculum Learning', 'Multi-Task Learning',
  'Federated Learning', 'Federated',
  'Causal Inference', 'Causal AI',
  'Synthetic Data', 'Data Augmentation', 'Mixup',
  'Active Learning', 'Bayesian Deep Learning',
  'Graph Neural Networks', 'GNN', 'Message Passing',
  'State Space Model', 'Mamba', 'Mamba-2', 'SSM',
  'Liquid Neural Networks', 'LNN',
  'Test-Time Compute', 'Inference-Time Scaling',
  'Constitutional AI',
  'Ensemble Methods', 'Stacking', 'Bagging',
  'Out-of-Distribution', 'OOD Detection',
  'Calibration', 'Temperature Scaling',
  'Watermarking', 'AI Detection',
  'Mechanistic Interpretability',

  // ── 框架 / 库 ──
  'PyTorch', 'TensorFlow', 'JAX', 'Keras', 'Flax', 'Haiku',
  'HuggingFace Transformers', 'Diffusers', 'Datasets', 'Accelerate', 'PEFT',
  'LangChain', 'LangGraph', 'LangChain Expression Language',
  'LlamaIndex', 'Haystack', 'DSPy', 'txtai',
  'Semantic Kernel', 'AutoGen', 'CrewAI',
  'FastAPI', 'Flask', 'Sanic',
  'ONNX', 'ONNX Runtime', 'OpenVINO', 'TensorRT', 'Core ML',
  'Apache TVM', 'MLIR',
  'Ray', 'Spark ML', 'Dask',
  'Triton Inference Server', 'TorchServe', 'BentoML',
  'Weave', 'Warp', 'Polars', 'DuckDB',
  'ZenML', 'Kedro', 'Metaflow', 'Prefect', 'Dagster',
  'MMEngine', 'MMDetection', 'MMSegmentation',
  'Detectron2', 'YOLO', 'YOLOv10', 'RT-DETR',
  'Transformers.js', 'ONNX Runtime Web', 'MediaPipe',

  // ── 向量数据库 ──
  'ChromaDB', 'Qdrant', 'Pinecone', 'Weaviate', 'Milvus',
  'pgvector', 'LanceDB', 'Elasticsearch', 'Vespa',
  'Redis', 'FAISS', 'Annoy', 'ScaNN', 'HNSW',

  // ── Agent 框架 ──
  'AI Agent', 'Multi-Agent', 'Agentic AI',
  'LangGraph', 'AutoGPT', 'BabyAGI', 'MetaGPT',
  'CrewAI', 'AutoGen', 'TaskWeaver',
  'Voyager', 'Gorilla', 'ToolBench',
  'Agent Protocol', 'A2A', 'MCP',
  'LLM Compiler', 'Plan-and-Execute',

  // ── 公司 / 机构 ──
  'OpenAI', 'Anthropic', 'Google DeepMind', 'Google AI',
  'Meta AI', 'Meta FAIR',
  'Mistral AI', 'Cohere', 'xAI', 'Stability AI',
  'Midjourney Inc', 'Runway ML', 'Pika Labs',
  'Black Forest Labs', 'Ideogram AI', 'Luma AI',
  'Hugging Face', 'Replicate', 'Together AI',
  'Scale AI', 'Labelbox', 'Snorkel',
  'Character.AI', 'Inflection AI', 'Adept AI',
  'Perplexity AI', 'Anysphere', 'Poolside',
  'Sakana AI', 'Liquid AI', 'Cartesia',
  'ElevenLabs', 'Suno Inc',

  // ── 国产 AI ──
  '百度文心', '文心一言', 'ERNIE',
  '阿里通义', '通义千问', 'Qwen',
  '字节豆包', '豆包', '豆包视觉',
  '腾讯混元', '混元大模型',
  '讯飞星火', 'SparkDesk',
  '智谱', '智谱清言', 'ChatGLM', 'CodeGeeX',
  '月之暗面', 'Moonshot', 'Kimi',
  '百川智能', 'Baichuan',
  'MiniMax', '海螺AI', 'Hailuo AI',
  '零一万物', 'Yi',
  '深度求索', 'DeepSeek',
  '面壁智能', 'MiniCPM', 'OpenBMB',
  '昆仑万维', 'Skywork',
  '上海AI Lab', '书生', 'InternLM',
  '阶跃星辰', 'Step-2',
  '生数科技', 'Vidu',
  '爱诗科技', 'PixVerse',
  '智象未来', 'HiDream',
  '云从科技', '云天励飞', '寒武纪',

  // ── 论文/学术 ──
  'Attention Is All You Need', 'BERT', 'GPT论文', 'ViT', 'ResNet',
  'Scaling Laws', 'Chinchilla',
  'LLaMA论文', 'Mistral论文', 'Gemini技术报告', 'GPT-4技术报告',
  'DPO论文', 'RLHF论文', 'Constitutional AI论文',
  'LoRA论文', 'QLoRA论文',
  'FlashAttention论文', 'FlashAttention-3',
  'Mamba论文', 'Mamba-2论文',
  'RAG论文', 'GraphRAG', 'Self-RAG', 'Corrective RAG',
  'Sora技术报告', 'DiT论文',
  'Toolformer', 'Gorilla论文', 'ReAct论文',

  // ── 数据集 ──
  'CommonCrawl', 'C4', 'FineWeb', 'The Pile', 'RedPajama',
  'Dolma', 'RefinedWeb', 'SlimPajama', 'DCLM',
  'SQuAD', 'GLUE', 'SuperGLUE', 'MMLU', 'HellaSwag',
  'HumanEval', 'MBPP', 'SWE-bench', 'GSM8K', 'MATH',
  'Alpaca', 'UltraChat', 'OpenHermes', 'ShareGPT',
  'WildChat', 'Chatbot Arena', 'LMSYS',
  'Flan', 'T0', 'Natural Instructions',
  'LAION', 'COCO', 'ImageNet', 'OpenImages',
  'LibriSpeech', 'Common Voice', 'FLEURS',
  'BigCode', 'The Stack', 'StarCoder',
  'Proof-Pile', 'OpenWebMath', 'Dolma-Math',
  'MMBench', 'MM-Vet', 'SEED-Bench', 'MMMU',
  'LooGLE', 'LongBench', 'RULER', 'BABILong',

  // ── 概念/术语 ──
  'AGI', 'ASI', 'Superintelligence',
  'Alignment', 'AI Safety', 'AI Ethics',
  'Hallucination', 'Factuality', 'Groundedness',
  'Context Window', '上下文长度', 'Long Context',
  'Scaling Law', 'Emergence', 'Grokking',
  'Token', 'Tokenization', 'Vocabulary',
  'Embedding', 'Latent Space', 'Representation',
  'Overfitting', 'Underfitting', 'Generalization',
  'Catastrophic Forgetting', 'Continual Learning',
  'Model Collapse', 'Data Contamination', 'Benchmark Leakage',
  'Red Teaming', 'Jailbreak', 'Prompt Injection',
  'RLHF Tax', 'Alignment Tax', 'Helpful-Harmless-Honest',
  'Intrinsic Evaluation', 'Extrinsic Evaluation',
  'Grounding', 'Tool Use', 'Function Calling', 'Code Interpreter',
  'Reasoning', 'Planning', 'World Model',
  'Foundation Model', 'Frontier Model', 'Open-source vs Closed',
  'AI Democratization', 'AI Accessibility',
  'Small Language Model', 'SLM', 'TinyML', 'On-device AI',
  'Green AI', 'Carbon Footprint', 'Energy Efficiency',

  // ── 应用领域 ──
  'Healthcare AI', 'Medical AI', 'Drug Discovery', 'Protein Folding',
  'AlphaFold', 'AlphaFold 3', 'ESMFold', 'RosettaFold',
  'Legal AI', 'LegalTech',
  'Education AI', 'EdTech', 'AI Tutor',
  'Finance AI', 'FinTech', 'AI Trading',
  'Coding AI', 'Software Engineering AI',
  'Creative AI', 'Generative Art', 'AI Music', 'AI Video',
  'Customer Service AI', 'Chatbot', 'AI客服',
  'Recruitment AI', 'HR AI',
  'Agriculture AI', 'Climate AI', 'Earth Science AI',
  'Robotics', 'Embodied AI', 'Robot Learning',
  'Autonomous Driving', 'Self-Driving', '端到端自动驾驶',
  'Gaming AI', 'Game AI', 'NPC AI',
  'Science AI', 'AI for Science', 'AI4Science',
  'Math AI', 'Theorem Proving', 'Lean',
  'Search AI', 'AI Search Engine',
  'Translation AI', 'NMT',
  'Summarization', '信息抽取', 'NER',

  // ── Prompt 工程 ──
  '提示词', 'Prompt', 'System Prompt',
  'Chain of Thought', 'CoT', 'Zero-shot CoT',
  'Few-Shot', 'One-Shot', 'Zero-Shot',
  'ReAct', 'Plan-and-Solve',
  'Tree of Thoughts', 'Graph of Thoughts',
  'Self-Consistency', 'Majority Voting',
  'Role Prompting', 'Persona Prompt',
  'Emotional Prompt', 'EmotionPrompt',
  'APE', 'Automatic Prompt Engineer',
  'OPRO', 'Prompt Optimization',
  'DSPy', 'Prompt Tuning', 'Soft Prompt', 'P-Tuning',
  'Instruction Tuning', 'IFT',
  'Constitutional Prompting',
  'Meta Prompting', 'Prompt Chaining',

  // ── 多模态 ──
  '多模态', 'Multimodal',
  'Vision Language Model', 'VLM',
  'GPT-4V', 'GPT-4o Vision', 'Claude Vision',
  'Gemini Vision', 'Gemini Pro Vision',
  'LLaVA', 'LLaVA-NeXT', 'CogVLM', 'CogVLM2',
  'Qwen-VL', 'InternVL', 'MiniGPT-4', 'mPLUG-Owl',
  'Flamingo', 'BLIP-2', 'InstructBLIP',
  'Image-to-Text', 'Text-to-Image', 'Image-to-Image',
  'Text-to-Video', 'Image-to-Video', 'Video-to-Text',
  'Text-to-Speech', 'TTS', 'Speech-to-Text', 'STT',
  'Any-to-Any', 'Omni-modal',
  'Image Understanding', 'Visual Grounding',
  'Visual QA', 'Document AI', 'OCR', 'LayoutLM',

  // ── 部署 / 运维 ──
  'Docker', 'Kubernetes', 'K8s',
  'AWS SageMaker', 'AWS Bedrock',
  'Google Vertex AI', 'Google AI Studio',
  'Azure AI', 'Azure OpenAI',
  'NVIDIA NIM', 'NVIDIA Triton', 'CUDA', 'cuDNN',
  'GPU', 'H100', 'A100', 'B100', 'B200', 'L40S', 'RTX 6000 Ada',
  'TPU', 'LPU', 'Inferentia', 'Trainium',
  'Model Serving', 'Inference Optimization', 'Batch Inference',
  'Load Balancing', 'Autoscaling', 'Cold Start',
  'Latency', 'Throughput', 'TTFT', 'TPOT',
  'CI/CD', 'MLOps', 'Model Registry',
  'Model Monitoring', 'Drift Detection', 'Data Drift',
  'A/B Testing', 'Canary Deployment', 'Shadow Deployment',
  'Cost Optimization', 'Token Economics',

  // ── AI 安全 ──
  'AI Safety', 'AI Security', 'AI Alignment',
  'RLHF', 'Constitutional AI', 'Red Teaming',
  'Jailbreak', 'Prompt Injection', 'PII Leakage',
  'Hallucination', 'Toxicity', 'Bias', 'Fairness',
  'Model Inversion', 'Membership Inference', 'Training Data Extraction',
  'Adversarial Attack', 'Adversarial Robustness',
  'Differential Privacy', 'Federated Learning Privacy',
  'Model Card', 'Data Card', 'System Card',
  'EU AI Act', 'AI Regulation', 'AI Governance',
  'AI Auditing', 'AI Compliance', 'Responsible AI',

  // ── 开源项目 / 社区热点 ──
  'OpenAI Whisper', 'OpenAI Triton', 'OpenAI Gym',
  'Stable Diffusion WebUI', 'ComfyUI',
  'LangChain', 'LlamaIndex', 'Dify',
  'Ollama', 'llama.cpp', 'mlc-llm',
  'vLLM', 'SGLang', 'Text Generation Inference',
  'Axolotl', 'Unsloth', 'LLaMA-Factory',
  'Open WebUI', 'LibreChat', 'LobeChat', 'NextChat',
  'ChatGPT-Next-Web', 'Chatbox',
  'FastChat', 'SGLang', 'LightLLM',
  'AutoGPT', 'GPT-Engineer', 'GPT-Pilot',
  'OpenDevin', 'SWE-Agent', 'Devin',
  'PrivateGPT', 'localGPT', 'GPT4All',
  'AnythingLLM', 'Quivr', 'Mem0',
  'Docling', 'Marker', 'Unstructured',
  'ColBERT', 'RAPTOR', 'GraphRAG-SDK',
  'Instructor', 'Outlines', 'Guidance', 'LMQL',
  'Sentence Transformers', 'FlagEmbedding', 'BGE',
  'Rerankers', 'Cross-Encoder', 'Cohere Rerank',
  'TGI', 'Triton Inference Server', 'BentoML',
  'SkyPilot', 'dstack', 'RunPod',
  'Oumi', 'distilabel', 'Argilla',
  'OpenRLHF', 'TRL', 'Axolotl',

  // ── 热门话题 / 讨论方向 ──
  '模型评测', 'Benchmark', 'Chatbot Arena',
  '本地部署', 'Local LLM', '离线AI',
  '性价比', '成本分析', 'TCO',
  '开源 vs 闭源', 'Open Source AI',
  'AGI 时间线', 'AI 未来',
  'AI 创业', 'AI 商业化', 'AI PMF',
  'AI 取代工作', 'AI 失业', 'AI 就业',
  'AI 教育', 'AI 学习路线', 'AI 入门',
  'AI 生产力', '效率提升', '工作流自动化',
  '数字人', 'AI 虚拟主播', 'AI 陪伴',
  'AI 写作', 'AI 编程', 'AI 翻译', 'AI 搜题',
  'AI 硬件', 'AI PC', 'AI 手机', 'NPU',
  'AI 芯片', 'AI Chip', 'AI 算力',
  'SaaS AI', 'AI API', 'AI MCP',
  '长文本', 'Long Context', '128K上下文', '1M上下文',
  '实时AI', 'Latency优化', '流式推理',
  '多语言', 'Multilingual', '中文能力',
  '幻觉问题', '事实性', 'RAG幻觉',

  // ══════════════════════════════════════════════
  // 中文标签扩展（约 1000 个）
  // 维度：国产模型 | 国内公司 | 技术概念 | 应用场景 | 社区热词
  //       | 开发工具 | AI绘画 | 学术研究 | 行业应用 | 模型评测
  //       | 部署硬件 | 开源项目 | 变现商业 | 安全伦理 | 教育学习
  //       | Prompt | RAG | Agent | 多模态 | 新兴话题
  // ══════════════════════════════════════════════

  // ── 国产大模型（系列/版本） ──
  '文心一言4.0', '文心一言3.5', '文心大模型', 'ERNIE 4.5', 'ERNIE Bot',
  '通义千问3.0', '通义千问2.5', '通义千问Max', '通义千问Plus', '通义千问Turbo',
  '豆包大模型', '豆包Pro', '豆包Lite', '豆包视觉', '火山方舟',
  '混元大模型', '混元Turbo', '混元Pro', '混元Large', '混元文生图',
  '讯飞星火4.0', '讯飞星火3.5', '星火认知大模型', 'Spark 4.0',
  '智谱GLM-4', 'GLM-4-Plus', 'GLM-4-Flash', 'GLM-4V', 'ChatGLM-6B',
  'Kimi Chat', 'Kimi 探索版', 'Moonshot v1', '月之暗面',
  '百川4', '百川3', '百川2', 'Baichuan4', 'Baichuan3-Turbo',
  'MiniMax-Text', 'MiniMax-VL', 'abab7', 'abab6.5',
  'Yi-Large', 'Yi-Medium', 'Yi-Vision', 'Yi-1.5', '零一万物',
  'DeepSeek V3', 'DeepSeek R1', 'DeepSeek Coder V2', 'DeepSeek VL2',
  '书生浦语', 'InternLM3', 'InternLM2.5', 'InternVL2', '书生万象',
  '面壁智能', 'MiniCPM-3', 'MiniCPM-V', 'OpenBMB',
  '天工大模型', 'Skywork', '昆仑万维', '天工4.0',
  'Step-2', 'Step-1V', '阶跃星辰',
  'TeleChat', '电信星辰', '星辰大模型',
  '孟子大模型', '澜舟科技', '孟子GPT',
  '元象XVERSE', 'XVERSE',
  '序列猴子', '出门问问', 'Mobvoi',
  'DeepSeek-R1-Distill', 'Qwen2.5-Coder', 'Qwen2.5-Math',

  // ── 国内AI公司/平台/产品 ──
  '百度智能云', '千帆大模型平台', '百度飞桨', 'PaddlePaddle',
  '阿里云', '百炼平台', '灵积', '阿里云百炼',
  '腾讯云', '腾讯混元开放平台', '腾讯元宝', '元宝',
  '字节跳动', '火山引擎', '扣子平台', '豆包MarsCode',
  '讯飞开放平台', '星火API',
  '智谱AI', '智谱开放平台', 'BigModel',
  '商汤科技', '商汤日日新', 'SenseNova', 'SenseChat',
  '旷视科技', 'Megvii', '依图科技', '云从科技',
  '科大讯飞', '思必驰', '云知声', '标贝科技',
  '硅基流动', 'SiliconCloud', 'SiliconFlow',
  '潞晨科技', 'Colossal-AI',
  '无问芯穹', 'Infinigence',
  '清昴智能', '清程智能',
  '趋境科技', 'ApproachingAI',
  '秘塔科技', '秘塔AI搜索', 'Metaso',
  'Monica', 'Monica.im',
  'HeyGem', 'HeyGem数字人',
  '阶跃星辰', '跃问',
  'LiblibAI', '哩布哩布', '堆友',
  '即梦AI', '即梦', 'Dreamina',
  '海螺AI', 'MiniMax海螺', 'HailuoAI',
  '可灵AI', 'KlingAI',
  'PixVerse', '爱诗科技',
  'Vidu', '生数科技',
  'HiDream', '智象未来',
  '奇点智源', '一览科技',
  '澜舟科技', '创新奇智', '第四范式',
  '思谋科技', '地平线', '寒武纪MLU', '燧原科技', '摩尔线程',

  // ── 中文技术概念 ──
  '大模型', '大语言模型', '语言模型', '基础模型',
  '预训练', '预训练模型', '持续预训练', '后训练',
  '有监督微调', '指令微调', '指令遵循', '对齐训练',
  '人类反馈强化学习', '偏好对齐', '价值对齐',
  '思维链', '思维树', '思维图', '逻辑推理',
  '上下文学习', '少样本学习', '零样本学习',
  '提示词工程', '提示词优化', '提示词模板',
  '模型幻觉', '事实性校验', '知识边界',
  '模型蒸馏', '知识蒸馏', '模型压缩',
  '量化部署', 'INT4量化', 'INT8量化', 'KV缓存量化',
  '参数高效微调', 'PEFT微调', 'Adapter微调',
  '模型评估', '评测基准', '能力评测', '红队测试',
  '模型安全', '内容安全', '输出审核', '护栏',
  '模型可解释性', '神经网络可解释', '特征分析',
  '涌现能力', '规模定律', '扩展律',
  '混合专家模型', '稀疏MoE', '稠密模型',
  '状态空间模型', '线性注意力', '长序列建模',
  '检索增强生成', '知识增强', '外部知识融合',
  '工具调用', '函数调用', '代码解释器',
  '规划能力', '推理能力', '数学推理', '多步推理',
  '多模态融合', '图文理解', '视觉语言对齐',
  '自回归生成', '流式生成', '并行解码',
  '对比学习', '表示学习', '自监督学习',
  '强化学习', '模仿学习', '偏好学习',
  '元学习', '少样本泛化', '领域适应',
  '灾难性遗忘', '持续学习', '增量学习',
  '数据飞轮', '数据闭环', '主动学习',
  '合成数据', '数据蒸馏', '数据配比',
  '词表扩展', '中文词表', '分词器', 'Tokenizer',

  // ── AI 应用场景（中文） ──
  '智能客服', 'AI客服', '机器人客服', '外呼机器人',
  '智能办公', 'AI办公', '文档处理', '会议纪要', 'AI周报',
  '智能写作', 'AI写作', '文案生成', '营销文案', '小红书文案',
  '智能编程', 'AI编程', '代码生成', '代码审查', '代码重构',
  '智能翻译', 'AI翻译', '实时翻译', '文档翻译', '字幕翻译',
  '智能搜索', 'AI搜索', '语义搜索', '企业搜索', '知识库搜索',
  '智能推荐', '个性化推荐', '内容推荐', '商品推荐',
  '智能问答', '知识问答', 'FAQ机器人', '文档问答',
  '智能语音', '语音识别', '语音合成', '语音克隆', '声音复刻',
  '数字人', 'AI主播', '虚拟数字人', '2D数字人', '3D数字人',
  '数字员工', 'AI员工', '虚拟员工', 'RPA+AI',
  '智能风控', '反欺诈', '信用评估', '风险预警',
  '智能投顾', 'AI投研', '量化交易', '智能研报',
  '智能诊断', 'AI辅诊', '医学影像', '病理分析',
  '药物发现', 'AI制药', '分子生成', '蛋白质预测',
  '智能教育', 'AI教育', '自适应学习', 'AI批改', 'AI出题',
  '智能司法', 'AI法律', '合同审查', '案例检索', '法规问答',
  '智能安防', 'AI安防', '人脸识别', '行为分析', '异常检测',
  '智能制造', '工业AI', '缺陷检测', '预测性维护', '工业视觉',
  '智能驾驶', '自动驾驶', '辅助驾驶', '端到端智驾',
  '智能座舱', '车载语音', '车载AI', '舱驾一体',
  '智能农业', 'AI农业', '病虫害识别', '产量预测',
  '智能能源', 'AI电网', '负荷预测', '新能源预测',
  '智能零售', 'AI零售', '智能选品', '销量预测', '无人店',
  '智能物流', 'AI物流', '路径规划', '仓储优化', '无人配送',

  // ── AI 绘画/设计/创意（中文） ──
  'AI绘画', 'AI画图', '文生图', '图生图',
  'AI写真', 'AI头像', 'AI换脸', '风格迁移',
  'AI设计', 'AI UI设计', 'AI海报', 'AI Banner',
  'AI视频', '文生视频', '图生视频', '视频风格化',
  'AI动画', 'AI短片', 'AI广告片', 'AI MV',
  'AI音乐', 'AI编曲', 'AI作词', 'AI唱歌',
  'AI配音', 'AI解说', 'AI播客', '有声书',
  'ControlNet', 'IP-Adapter', 'InstantID', 'IPAdapter-FaceID',
  '工作流', 'ComfyUI工作流', '节点工作流',
  '提示词', '画图提示词', '正向提示词', '负向提示词',
  '采样器', '采样步数', 'CFG Scale', '高分辨率修复',
  '图生图重绘', 'Inpaint', 'Outpaint', '扩图',
  '光影控制', '构图控制', '姿态控制', '深度控制',
  '背景替换', '物体移除', 'AI修图', 'AI扩图',
  '老照片修复', '黑白上色', '画质增强', '超分辨率',
  '表情包生成', '梗图生成', 'AI表情包', 'AI梗图',

  // ── AI 编程/开发（中文） ──
  'AI编程助手', '代码补全', '智能代码生成', 'AI Debug',
  '低代码', '无代码', '零代码', '可视化开发',
  'AI测试', '自动化测试', '测试用例生成', 'AI单元测试',
  'AI DevOps', '智能运维', '日志分析', '告警降噪',
  'API网关', '模型网关', '统一API', '多模型路由',
  '向量数据库', '知识库', '向量检索', '语义索引',
  '模型训练', '分布式训练', '混合精度训练', 'ZeRO优化',
  '模型部署', '模型服务化', '在线推理', '离线推理',
  '模型管理', '模型版本', '模型注册', '模型血缘',
  '数据标注', '数据清洗', '数据治理', '数据管道',
  '特征工程', '特征存储', '特征平台',
  '实验管理', '实验追踪', '超参搜索', '自动调参',
  'CI/CD for ML', '持续训练', '持续部署', '自动化流水线',
  '微服务', 'Serverless', '容器化部署', '边缘部署',

  // ── AI 硬件/算力（中文） ──
  'GPU服务器', '算力租赁', 'GPU云', '算力平台',
  '国产GPU', '昇腾', '寒武纪', '壁仞', '天数智芯', '摩尔线程GPU',
  '华为昇腾', '昇腾910B', '昇腾310', 'CANN', '昇思MindSpore',
  'NPU', 'TPU', 'LPU', 'AI芯片', '推理芯片',
  '模型压缩', '推理加速', 'TensorRT-LLM', 'vLLM部署',
  '显存优化', '内存优化', 'Offload', 'CPU推理',
  '端侧推理', '移动端部署', 'MNN', 'TNN', 'NCNN',
  '量化工具', '模型转换', 'ONNX导出', 'TorchScript',
  'AI算力中心', '智算中心', '超算中心', '东数西算',

  // ── 开源社区/项目（中文） ──
  '魔搭社区', 'ModelScope', '阿里魔搭',
  '飞桨社区', 'PaddlePaddle',
  'OpenI启智', '启智社区',
  '矩池云', '趋动云', '揽睿星舟', 'AutoDL',
  'Gitee AI', '开源中国',
  'HuggingFace中文', 'HF Mirror', '镜像站',
  'LLaMA-Factory中文', 'Firefly微调',
  'ChatGLM开源', 'Qwen开源', 'DeepSeek开源',
  '书生开源', 'InternLM开源',
  'OpenRLHF', 'trlX', 'DeepSpeed', 'Megatron',
  'LangChain-ChatChat', 'LangChain-ChatGLM',
  'FastGPT', 'MaxKB', 'Dify中文', 'RAGFlow中文',
  'One-API', 'New-API', 'AIHubMix',
  'ChatGPT-Next-Web', 'LobeChat中文', 'Chatbox中文',

  // ── 中文社区热词/讨论话题 ──
  'AI卷', '大模型卷', '模型同质化', '百模大战',
  'AI变现', 'AI副业', 'AI赚钱', 'AI创业项目',
  'AI焦虑', 'AI失业', '被AI取代', 'AI裁员',
  '提示词工程师', 'AI产品经理', 'AI训练师', 'AI运营',
  '大模型落地', '行业大模型', '垂直领域大模型', '领域微调',
  '私有化部署', '数据不出域', '合规部署', '信创适配',
  '模型选型', '模型对比', '模型横评', '性价比对比',
  '闭源vs开源', '开源追赶', '开源模型能力',
  'Llama替代', 'GPT替代', '国产替代',
  '企业级AI', '生产级AI', '高可用AI',
  'token消耗', 'API费用', '推理成本', '模型性价比',
  '上下文窗口', '长文本支持', '128k够用吗', '无限上下文',
  'Prompt技巧', '提示词模板分享', '万能提示词',
  'AI工作流', '自动化工作流', 'Agent工作流',
  'AI时代技能', 'AI学习路径', 'AI入门指南', 'AI进阶',
  '程序员转型', 'AI时代生存', '技术人出路',
  'AI做副业', '自媒体AI', 'AI内容创业',
  '数字人直播', 'AI直播', '无人直播', '24小时直播',
  'RPA自动化', '浏览器自动化', 'AI+RPA',
  'AI写论文', 'AI辅助科研', '论文润色', '文献综述',
  'AI做PPT', 'AI做Excel', 'AI日报', 'AI总结',
  'AI面试', 'AI刷题', 'AI改简历',
  'AI选股', 'AI看盘', '量化散户',

  // ── AI 变现/商业（中文） ──
  '大模型商业模式', 'API定价', '按量计费', '会员订阅',
  'AI订阅', 'AI SaaS', 'AI工具付费', 'AI出海',
  'GPTs商店', 'AI应用商店', '插件生态', 'Agent市场',
  'AI融资', 'AI估值', 'AI泡沫', 'AI寒冬',
  'AI PMF', '产品市场契合', 'AI增长', 'AI留存',
  'AI场景', '高频场景', '刚需场景', '低频场景',
  'AI幻觉成本', '准确率要求', '容错率',
  'ROI计算', '投入产出比', '降本增效', 'AI增效',
  '数据壁垒', '模型壁垒', '技术护城河', '先发优势',
  '开源商业模式', '开放权重', '开源vs商业',

  // ── AI 学习/教育（中文） ──
  '吴恩达', '李沐', '李宏毅', '动手学深度学习',
  'CS229', 'CS231n', 'CS224n', '吴恩达机器学习',
  '李宏毅机器学习', '李沐论文精读',
  '神经网络入门', '深度学习入门', '机器学习入门', '零基础学AI',
  'Python入门', 'PyTorch教程', 'Transformers教程',
  '论文带读', '论文复现', '论文解读', 'ArXiv精选',
  'AI面试题', '大模型面试', '算法面试',
  'AI认证', 'AI证书', 'NVIDIA认证', 'TensorFlow认证',
  'AI比赛', '打比赛', 'Kaggle', '天池大赛', 'AI挑战赛',
  '学习路线图', 'AI知识图谱', 'AI技能树',
  'AI课程推荐', 'AI书籍推荐', 'AI学习资源',
  '机器学习工程师', '深度学习工程师', 'NLP工程师', 'CV工程师',
  '大模型算法岗', '推理优化岗', 'AI Infra岗',

  // ── Prompt 工程（中文） ──
  '系统提示词', '角色设定', '人设Prompt', '角色扮演',
  '结构化提示词', 'Markdown提示词', 'XML提示词',
  '逐步思考', '分步推理', 'Let us think step by step',
  '给示例', 'Few-shot示例', '示例学习',
  '思维链提示', '零样本思维链', '自动思维链',
  '自我一致性', '多数投票', '多路径推理',
  '反思提示', '自我修正', 'Self-Refine',
  '角色扮演提示', '专家角色', '多角色对话',
  '情绪提示', '情感Prompt', '鼓励式Prompt',
  '反向提示', '负面示例', '不说教Prompt',
  '长文提示词', '系统指令', '规则约束',
  '输出格式控制', 'JSON输出', '结构化输出',
  'DSPy编程', '提示词自动优化', '提示词版本管理',
  'Prompt注入', '提示词泄露', '提示词安全',
  '越狱提示词', ' Jailbreak检测', '提示词加固',

  // ── RAG/知识增强（中文） ──
  '知识库搭建', 'RAG入门', 'RAG实战', 'RAG踩坑',
  '文档解析', 'PDF解析', '表格解析', 'PPT解析',
  '文档切分', '语义切分', '句子切分', '段落切分',
  'Embedding模型', 'BGE中文', 'text2vec', 'M3E',
  '向量召回', '稀疏召回', '混合检索', '多路召回',
  '重排序', 'Reranker', 'BGE-Reranker', 'Cross-Encoder',
  'RAG评估', 'RAGAS', '检索命中率', '答案准确率',
  'GraphRAG', '知识图谱RAG', 'LightRAG', 'KAG',
  '多模态RAG', '图片检索', '视频检索', '音频检索',
  'RAG优化', '检索增强', 'HyDE', '查询改写',
  'RAG架构', 'RAG流水线', 'RAG工程化',

  // ── AI Agent（中文） ──
  '智能体', 'AI智能体', 'Agent开发',
  '多Agent', '多智能体协作', 'Agent协作',
  'Agent框架', 'Agent编排', 'Agent工作流',
  '自主Agent', '半自主Agent', '人机协同Agent',
  '工具调用Agent', '代码执行Agent', '浏览器Agent',
  '记忆模块', 'Agent记忆', '短期记忆', '长期记忆',
  '反思机制', '自我反思Agent', '自我改进',
  '规划Agent', '执行Agent', 'Plan-Execute',
  '角色扮演Agent', '对话Agent', '任务Agent',
  'Multi-Agent辩论', 'Agent评审', 'Agent投票',
  'Agent安全', 'Agent权限', '沙箱Agent',
  'Agent评测', 'AgentBench', 'SWE-bench评测',
  'MCP协议', 'Agent通信', 'Agent互联',
  'Agent落地', '企业Agent', '个人Agent', 'Agent产品',

  // ── 多模态（中文） ──
  '图文理解', '图片描述', '看图说话', '图片问答',
  '视频理解', '视频摘要', '视频问答', '视频定位',
  '音频理解', '音乐理解', '环境音识别', '声纹识别',
  '文档理解', 'OCR识别', '公式识别', '手写识别',
  '视觉推理', '空间推理', '物理推理',
  '跨模态检索', '文搜图', '图搜文', '以图搜图',
  '多模态对话', '语音对话', '视频对话', '实时对话',
  '端到端多模态', '原生多模态', '全模态',
  '视觉-语言模型', 'VLM能力', 'VLM落地',

  // ── AI 安全/伦理（中文） ──
  'AI伦理', '算法偏见', '数据偏见', '公平性',
  '隐私保护', '数据脱敏', '差分隐私', '联邦学习',
  '模型安全', '对抗攻击', '后门攻击', '投毒攻击',
  '价值观对齐', '安全对齐', '无害性', '有用性',
  '内容审核', '敏感词过滤', '输出安全', '合规输出',
  'AI监管', '算法备案', '大模型备案', '生成式AI监管',
  '深度伪造', 'Deepfake', 'AI诈骗', 'AI换脸诈骗',
  'AI版权', '训练数据版权', '生成内容版权', 'AI创作归属',
  '开源合规', '开源协议', 'Apache协议', 'MIT协议',
  'AI可解释', '模型审计', '第三方评测', '安全评测',

  // ── AI 最新热点/趋势（中文） ──
  '推理模型', 'Reasoning Model', 'o1类模型', '慢思考',
  '推理时扩展', 'Test-Time Compute', '推理预算',
  'AI搜索', '深度搜索', '搜索增强', '搜索即答案',
  'AI操作系统', 'AI OS', 'AI native应用',
  'AI浏览器', 'AI终端', 'AI眼镜', 'AI耳机',
  '具身智能', '人形机器人', '灵巧手', '机械臂AI',
  '世界模型', '视频生成世界模型', 'Sora类模型',
  'AI for Science', 'AI4Science', 'AI科研',
  'AI编程Agent', '全自动编程', 'AI软件工程师',
  'AI游戏', 'AI NPC', 'AI生成游戏', '无限游戏',
  '实时语音', '打断式对话', '全双工语音', '语音情感',
  '长上下文', '无限上下文', '终身记忆', '个性化记忆',
  '多Agent社会', 'Agent文明', 'Agent组织',
  'AI短视频', 'AI短剧', 'AI电视剧', 'AI电影',
  '合成数据训练', '自我对弈', '自我改进', '自我进化',
  '端侧大模型', '手机跑大模型', '离线大模型', '隐私AI',
  '乐高式AI', '模块化AI', '可组合AI',
  'AI产品经理', 'PM x AI', '设计师 x AI',
  'AI评测标准', '中文评测集', '国产评测基准',

  // ── 行业大模型/垂直应用（中文） ──
  '金融大模型', '医疗大模型', '法律大模型', '教育大模型',
  '工业大模型', '政务大模型', '科研大模型', '媒体大模型',
  '金融AI应用', '智能风控AI', '智能营销AI', '智能投研AI',
  '医疗AI应用', '影像AI', '病理AI', '临床决策AI',
  '法律AI应用', '合同AI', '法律咨询AI', '审判辅助AI',
  '教育AI应用', '学情分析AI', '精准教学AI', 'AI班主任',
  '传媒AI应用', 'AI写稿', 'AI剪辑', 'AI媒资管理',
  '体育AI', 'AI赛事分析', 'AI裁判', 'AI训练辅助',

  // ── 数据/评测（中文） ──
  '中文数据集', '中文评测', '中文基准',
  'C-Eval', 'CMMLU', 'SuperCLUE', 'FlagEval',
  'OpenCompass', '司南评测', 'MaaS评测',
  'GAOKAO', '高考评测', '法律考试评测', '医学考试评测',
  '中文对齐评测', '中文安全性评测', '中文能力评测',
  'Chatbot Arena CN', '中文竞技场', 'LMSYS中文',
  '对齐评测', '红队评测', '越狱评测',
  '长文本评测', 'LongBench CN', '大海捞针',
  '幻觉评测', '事实性评测', 'HaluEval CN',
  'Agent评测CN', '工具调用评测', '代码评测CN',
]

/** 获取热门标签列表 */
export function listTags(): string[] {
  return TAGS
}

/**
 * 分类服务。
 * 板块列表由 constants/business.ts 统一控制（后端是唯一数据源），
 * 这里负责叠加数据库里的真实帖子数统计。
 */

/** 单个板块信息 */
export interface CategoryItem {
  /** 板块 slug，即帖子 category 字段值 */
  slug: string
  /** 板块中文名 */
  name: string
  /** 板块 emoji 图标 */
  icon: string
  /** 该板块下的帖子总数 */
  postCount: string
}

/**
 * 获取全部分类（含真实帖子数）。
 * 按 category 分组统计，一次查询取全量，避免 N+1。
 */
export async function listCategories(): Promise<CategoryItem[]> {
  const grouped = await prisma.post.groupBy({
    by: ['category'],
    _count: { _all: true },
  })

  const countMap = new Map(grouped.map((g) => [g.category, g._count._all]))

  return Object.values(Category).map((slug) => ({
    slug,
    name: CategoryLabel[slug],
    icon: CategoryIcon[slug],
    postCount: String(countMap.get(slug) ?? 0),
  }))
}
